version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: python3
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8080

